[package]
name = "rusty-2048"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
crossterm = "0.26.0"
matrix_display = "1.0.0"
rand = "0.8.5"
